from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class SearchResult(BaseModel):
    source: str = Field(default="", description="Source that produced the result.")
    title: str = Field(default="", description="Result title.")
    url: str = Field(default="", description="Canonical result URL.")
    discussion_url: str = Field(default="", description="Public discussion URL when the source provides one.")
    repo: str = Field(default="", description="Public repository identifier when the source provides one.")
    version: str = Field(default="", description="Release version when the source provides one.")
    release_notes: str = Field(default="", description="Public release notes when the source provides them.")
    commit_sha: str = Field(default="", description="Commit SHA when the source provides one.")
    short_sha: str = Field(default="", description="Short commit SHA when the source provides one.")
    commit_url: str = Field(default="", description="Public GitHub commit URL when available.")
    api_url: str = Field(default="", description="Public API URL when available.")
    parent_count: int = Field(default=0, description="Commit parent count when available.")
    verification_status: str = Field(default="", description="Commit verification status when available.")
    changed_files: List[str] = Field(default_factory=list, description="Changed file paths when detail is available.")
    additions: int = Field(default=0, description="Commit additions when detail is available.")
    deletions: int = Field(default=0, description="Commit deletions when detail is available.")
    classification: str = Field(default="", description="Deterministic source classification.")
    importance: str = Field(default="", description="Deterministic importance label.")
    confidence: str = Field(default="", description="Deterministic confidence label.")
    rationale: str = Field(default="", description="Why the item was selected or classified.")
    source_type: str = Field(default="", description="Specific public source type.")
    arxiv_id: str = Field(default="", description="arXiv identifier when available.")
    abstract: str = Field(default="", description="Public paper abstract when available.")
    authors: List[str] = Field(default_factory=list, description="Public paper authors when available.")
    updated_at: str = Field(default="", description="Updated date when available.")
    categories: List[str] = Field(default_factory=list, description="Public paper categories when available.")
    primary_category: str = Field(default="", description="Primary paper category when available.")
    abstract_url: str = Field(default="", description="Public abstract URL when available.")
    pdf_url: str = Field(default="", description="Public PDF URL when available.")
    model_id: str = Field(default="", description="Public model identifier when available.")
    downloads: int = Field(default=0, description="Public model downloads when available.")
    created_at: str = Field(default="", description="Created date when available.")
    last_modified: str = Field(default="", description="Last modified date when available.")
    pipeline_tag: str = Field(default="", description="Model pipeline tag when available.")
    hf_tags: List[str] = Field(default_factory=list, description="Public Hugging Face tags when available.")
    license: str = Field(default="", description="Public license when available.")
    model_url: str = Field(default="", description="Public model URL when available.")
    paper_url: str = Field(default="", description="Related paper URL when available.")
    github_url: str = Field(default="", description="Related GitHub URL when available.")
    description: str = Field(default="", description="Public model description when available.")
    language: str = Field(default="", description="Repository language when available.")
    stars: int = Field(default=0, description="Public repository stars when available.")
    stars_today: int = Field(default=0, description="Public daily star growth when available.")
    topics: List[str] = Field(default_factory=list, description="Public repository topics when available.")
    author: str = Field(default="", description="Public author, channel, source, or publisher when available.")
    date: Optional[str] = Field(default=None, description="Published date or indexed date when available.")
    summary: str = Field(default="", description="Short result summary.")
    full_text: str = Field(default="", description="Full public text when available from the source.")
    image_url: str = Field(default="", description="Image or thumbnail URL when available.")
    video_url: str = Field(default="", description="Video URL when available.")
    likes: Optional[int] = Field(default=None, description="Public like/upvote count when available.")
    comments: Optional[int] = Field(default=None, description="Public comment/reply count when available.")
    shares: Optional[int] = Field(default=None, description="Public share/repost count when available.")
    views: Optional[int] = Field(default=None, description="Public view count when available.")
    reason_selected: str = Field(default="", description="Why the result was selected for the query.")
    score: float = Field(default=0, description="Internal relevance and recency score used for ranking.")
    tags: List[str] = Field(default_factory=list, description="Simple tags inferred from source and query terms.")
